name: Build and Publish APK

on:
  push:
    branches:
      - main  # 当代码推送到 main 分支时触发构建

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
    # 检出代码
    - name: Checkout code
      uses: actions/checkout@v3

    # 设置 JDK 环境
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin' # 或其他JDK提供商如 zulu、adopt
        java-version: '17'

    # 设置 Android SDK 环境
    - name: Setup Android SDK
      uses: android-actions/setup-android@v2
      with:
        api-level: 31       # 设置目标API级别
        build-tools: 31.0.0 # 设置构建工具版本
        ndk: true           # 可选，是否安装NDK

    # 构建 APK
    - name: Build Release APK
      run: |
        chmod +x ./gradlew
        ./gradlew assembleRelease

    # 上传生成的 APK 作为构建工件
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: app-release.apk
        path: app/build/outputs/apk/release/app-release.apk
